sudo: required

services:
  - docker

before_install:
  - docker build -t robmccarthy/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run robmccarthy/react-test npm test -- --coverage

after_success:
  - docker build -t robmccarthy/multi-client ./client
  - docker build -t robmccarthy/multi-nginx ./nginx
  - docker build -t robmccarthy/multi-server ./server
  - docker build -t robmccarthy/multi-worker ./worker
# Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Take those images and push them to docker hub
  - docker push robmccarthy/multi-client
  - docker push robmccarthy/multi-nginx
  - docker push robmccarthy/multi-server
  - docker push robmccarthy/multi-worker
